version: '2'

services:
    apache:
        build: ./
        container_name: sascom-web-server
        ports:
            - 2907:80
        volumes:
            - ./code:/app
        links:
            - db
        environment:
            - APACHE_SERVER_NAME=sascom.api
            - PHP_SHORT_OPEN_TAG=On
            - PHP_ERROR_REPORTING=E_ALL
            - PHP_DISPLAY_ERRORS=On
            - PHP_HTML_ERRORS=On
        networks:
            report:
                aliases:
                    - web-server
    db:
        image: mysql:5.6
        container_name: sascom-database
        ports:
            - "3333:3306"
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: sascom
            # MYSQL_USER: root
            # MYSQL_PASSWORD: admin
        networks:
            report:
                aliases:
                    - database

networks:
    report:
        driver: bridge